name: CD Pipeline
on:
    workflow_run:
        workflows: ['CI Pipeline']
        types:
            - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull docker container
        run: sudo docker pull sellay2025/app:latest
      - name: Delete old docker container
        run: sudo docker rm -f app-container || true
      - name: Run Docker container
        run: docker run -d -p 3333:3333 --name app-container sellay2025/app