name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
   # - uses: actions/checkout@v4
   # - name: Login Docker 
   #   run: docker login -u $DOCKER_LOGIN -p ${DOCKER_PASSWORD}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sellay2025/app:$(date +%s)

